# Generated by Django 2.1.2 on 2020-06-23 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='User',
        ),
    ]
