# Generated by Django 2.2.9 on 2020-06-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='company',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
