# Generated by Django 2.2.9 on 2020-06-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='approval_authority',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='cargoes_permitted',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='operation_type',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='port_fees_vessels',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='vessels_size_permitted',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
